# Generated by Django 5.0.4 on 2024-04-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.AutoField(primary_key=True, serialize=False)),
                ('name_subject', models.CharField(max_length=255)),
                ('description_subject', models.CharField(max_length=255, null=True)),
                ('photo_subject', models.ImageField(default=True, null=True, upload_to='Images/images_subjects')),
            ],
        ),
    ]
