# Generated by Django 5.0.4 on 2024-04-29 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_LearnApp_Admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id_classroom', models.AutoField(primary_key=True, serialize=False)),
                ('name_classroom', models.CharField(max_length=255)),
                ('custom_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('subject', models.ManyToManyField(to='E_LearnApp_Admin.subject')),
            ],
        ),
    ]
