# Generated by Django 5.0.4 on 2024-05-23 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_LearnApp_Admin', '0002_classroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id_chapter', models.AutoField(primary_key=True, serialize=False)),
                ('title_chapter', models.CharField(max_length=150)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_LearnApp_Admin.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('title_Course', models.CharField(max_length=150)),
                ('description_course', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_LearnApp_Admin.subject')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id_lesson', models.AutoField(primary_key=True, serialize=False)),
                ('title_lesson', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
                ('file_content', models.FileField(blank=True, null=True, upload_to='Lessons')),
                ('chapters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_LearnApp_Admin.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_LearnApp_Admin.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id_module', models.AutoField(primary_key=True, serialize=False)),
                ('title_module', models.CharField(max_length=150)),
                ('chapters', models.ManyToManyField(to='E_LearnApp_Admin.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_LearnApp_Admin.course')),
            ],
        ),
    ]
